// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DialogsColumns holds the columns for the "dialogs" table.
	DialogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sid", Type: field.TypeInt},
		{Name: "user", Type: field.TypeString, Default: ""},
		{Name: "assistant", Type: field.TypeString, Default: ""},
		{Name: "error", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
	}
	// DialogsTable holds the schema information for the "dialogs" table.
	DialogsTable = &schema.Table{
		Name:       "dialogs",
		Columns:    DialogsColumns,
		PrimaryKey: []*schema.Column{DialogsColumns[0]},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uid", Type: field.TypeString, Default: ""},
		{Name: "error", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DialogsTable,
		SessionsTable,
	}
)

func init() {
}
