// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/qyqx233/chat-go-api/ent/dialog"
	"github.com/qyqx233/chat-go-api/ent/predicate"
)

// DialogDelete is the builder for deleting a Dialog entity.
type DialogDelete struct {
	config
	hooks    []Hook
	mutation *DialogMutation
}

// Where appends a list predicates to the DialogDelete builder.
func (dd *DialogDelete) Where(ps ...predicate.Dialog) *DialogDelete {
	dd.mutation.Where(ps...)
	return dd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dd *DialogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, DialogMutation](ctx, dd.sqlExec, dd.mutation, dd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dd *DialogDelete) ExecX(ctx context.Context) int {
	n, err := dd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dd *DialogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(dialog.Table, sqlgraph.NewFieldSpec(dialog.FieldID, field.TypeInt))
	if ps := dd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dd.mutation.done = true
	return affected, err
}

// DialogDeleteOne is the builder for deleting a single Dialog entity.
type DialogDeleteOne struct {
	dd *DialogDelete
}

// Where appends a list predicates to the DialogDelete builder.
func (ddo *DialogDeleteOne) Where(ps ...predicate.Dialog) *DialogDeleteOne {
	ddo.dd.mutation.Where(ps...)
	return ddo
}

// Exec executes the deletion query.
func (ddo *DialogDeleteOne) Exec(ctx context.Context) error {
	n, err := ddo.dd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dialog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ddo *DialogDeleteOne) ExecX(ctx context.Context) {
	if err := ddo.Exec(ctx); err != nil {
		panic(err)
	}
}
