// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/qyqx233/chat-go-api/ent/dialog"
	"github.com/qyqx233/chat-go-api/ent/schema"
	"github.com/qyqx233/chat-go-api/ent/session"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	dialogFields := schema.Dialog{}.Fields()
	_ = dialogFields
	// dialogDescUser is the schema descriptor for user field.
	dialogDescUser := dialogFields[1].Descriptor()
	// dialog.DefaultUser holds the default value on creation for the user field.
	dialog.DefaultUser = dialogDescUser.Default.(string)
	// dialogDescAssistant is the schema descriptor for assistant field.
	dialogDescAssistant := dialogFields[2].Descriptor()
	// dialog.DefaultAssistant holds the default value on creation for the assistant field.
	dialog.DefaultAssistant = dialogDescAssistant.Default.(string)
	// dialogDescError is the schema descriptor for error field.
	dialogDescError := dialogFields[3].Descriptor()
	// dialog.DefaultError holds the default value on creation for the error field.
	dialog.DefaultError = dialogDescError.Default.(string)
	// dialogDescCreatedAt is the schema descriptor for created_at field.
	dialogDescCreatedAt := dialogFields[4].Descriptor()
	// dialog.DefaultCreatedAt holds the default value on creation for the created_at field.
	dialog.DefaultCreatedAt = dialogDescCreatedAt.Default.(func() time.Time)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescUID is the schema descriptor for uid field.
	sessionDescUID := sessionFields[0].Descriptor()
	// session.DefaultUID holds the default value on creation for the uid field.
	session.DefaultUID = sessionDescUID.Default.(string)
	// sessionDescError is the schema descriptor for error field.
	sessionDescError := sessionFields[1].Descriptor()
	// session.DefaultError holds the default value on creation for the error field.
	session.DefaultError = sessionDescError.Default.(string)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[2].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
}
