// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Dialog is the predicate function for dialog builders.
type Dialog func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)
